import type { Metadata } from "next";
import Link from "next/link";
import { AUTHORS } from "@/lib/content/authors";
import { ARTICLES } from "@/lib/content/articles";
import { REPORTS } from "@/lib/content/reports";
import { CARDS } from "@/lib/catalog";
import { SETS } from "@/lib/riftbound";
import { ACCOUNTS_ENABLED, CONTACT_EMAIL, OFFICIAL_CARD_DB_URL, PRICES_ARE_DEMO, SITE_NAME, SITE_URL } from "@/lib/site";
import { riftcompareUrl } from "@/lib/affiliate";

export const metadata: Metadata = {
  title: "About & Disclaimers",
  description: `What ${SITE_NAME} is, where its data comes from, and which parts of it are demo content. An unofficial Riftbound TCG price tracker, not affiliated with Riot Games.`,
  alternates: { canonical: `${SITE_URL}/about` },
};

function Section({ id, title, children }: { id?: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="mt-8">
      <h2 className="font-display text-[22px] uppercase tracking-wide text-ink">{title}</h2>
      <div className="mt-2.5 space-y-3 text-[14.5px] leading-relaxed text-ink-muted">{children}</div>
    </section>
  );
}

export default function AboutPage() {
  return (
    <div className="max-w-[72ch]">
      <h1 className="font-display text-3xl uppercase tracking-wide text-ink sm:text-4xl">About &amp; Disclaimers</h1>
      <p className="mt-2 text-[15px] leading-relaxed text-ink-muted">
        {SITE_NAME} tracks singles prices for Riftbound: League of Legends Trading Card Game — daily movers, price
        history and market analysis, in the shape of a financial dashboard.
      </p>

      {PRICES_ARE_DEMO && (
        <div className="mt-5 rounded-xl border border-down/40 bg-down/10 p-4">
          <h2 className="font-display text-[17px] uppercase tracking-wide text-down">Read this first</h2>
          <p className="mt-1.5 text-[14px] leading-relaxed text-ink-muted">
            This build is a <strong className="font-semibold text-ink">demonstration</strong>. The card names, sets,
            rarities, domains and artwork are real. <strong className="font-semibold text-ink">The prices are not.</strong>{" "}
            Every figure on this site is generated by an algorithm, and every article and author is invented. Do not
            make a buying, selling or trading decision on anything you read here.
          </p>
        </div>
      )}

      <Section title="Not affiliated with Riot Games">
        <p>
          {SITE_NAME} is an unofficial fan project. It is not affiliated with, endorsed, sponsored or specifically
          approved by Riot Games, Inc. Riftbound, League of Legends, and all associated names, marks, logos and card
          images are trademarks or copyrights of Riot Games. Card artwork is displayed for identification and reference.
        </p>
        <p>
          For authoritative card text, rules and legality, use{" "}
          <a href={OFFICIAL_CARD_DB_URL} target="_blank" rel="noopener noreferrer" className="text-accent hover:underline">
            Riot&apos;s official Riftbound card database
          </a>
          . This site deliberately does not reproduce or invent card ability text.
        </p>
      </Section>

      <Section id="prices" title="Where the prices come from">
        <p>
          The site is designed around <strong className="font-semibold text-ink">TCGplayer Market Price</strong> — the
          fair-market figure derived from completed sales, rather than the cheapest active listing (which on any TCG
          marketplace is routinely a damaged or foreign-language copy). Low, Average, Market, Foil and Market Foil are
          stored per printing, with one snapshot per day.
        </p>
        {PRICES_ARE_DEMO ? (
          <p>
            <strong className="font-semibold text-down">In this build, no TCGplayer key is configured</strong>, so the
            prices you see are produced by a generator (a deterministic function of the card and the calendar date). They
            are plausible-looking and completely fictional. The generator lives behind the same adapter interface a live
            TCGplayer feed plugs into, so switching to real data changes one function and no pages.
          </p>
        ) : (
          <p>
            Prices are sourced from TCGplayer. They are reference figures, not offers to buy or sell, and will differ
            from what any individual seller charges. TCGplayer is not affiliated with this site.
          </p>
        )}
      </Section>

      <Section id="affiliate" title="How this site makes money">
        <p>
          {SITE_NAME} is a <strong className="font-semibold text-ink">TCGplayer affiliate</strong>. Every &quot;Buy&quot;
          link on the site is an affiliate link: if you buy after following one, we earn a commission — at no extra cost
          to you. Those links are marked <code className="font-mono text-[13px] text-ink">rel=&quot;sponsored&quot;</code>{" "}
          in the page source as well as being labelled on screen.
        </p>
        <p>
          <strong className="font-semibold text-ink">Commission does not influence the data.</strong> There is only one
          merchant here, so there is no ranking to bias — but the principle matters anyway: prices, movers and charts
          are produced from the pricing data alone. Nothing is promoted, reordered or hidden because of what it pays.
        </p>
        <p>
          Links to <a href={riftcompareUrl("", "about")} target="_blank" rel="noopener" className="text-accent hover:underline">RiftCompare</a>,
          our sister site, are <em>not</em> affiliate links — it is run by the same people and pays nothing.
        </p>
      </Section>

      <Section id="authors" title="The authors are fictional">
        <p>
          The {AUTHORS.filter((a) => !a.isDesk).length} human-looking bylines on this site are{" "}
          <strong className="font-semibold text-ink">invented personas</strong>. None of them is a real person, none is
          based on a real person, and no real writer&apos;s name, likeness, biography or work has been used. They exist
          so the article templates have something to render.
        </p>
        <p>
          Their avatars are procedurally generated abstract shapes, not faces. Photographs of real people were never an
          option; even synthetic photorealistic faces were rejected, because a convincing &quot;photo&quot; invites you
          to believe there is someone behind the byline — which is exactly the impression a roster of invented authors
          must not create.
        </p>
        <ul className="mt-3 grid gap-2 sm:grid-cols-2">
          {AUTHORS.filter((a) => !a.isDesk).map((a) => (
            <li key={a.slug} className="flex items-center gap-2.5 rounded-lg border border-line bg-surface-1 p-2.5">
              <img src={a.avatar} alt="" width={36} height={36} className="h-9 w-9 shrink-0 rounded-full" />
              <span className="min-w-0">
                <span className="block truncate text-[13.5px] font-semibold text-ink">{a.name}</span>
                <span className="block truncate text-[11.5px] text-ink-dim">{a.role} · fictional persona</span>
              </span>
            </li>
          ))}
        </ul>
      </Section>

      <Section id="editorial" title="Two kinds of article">
        <p>
          The {ARTICLES.length} pieces under{" "}
          <Link href="/news" className="text-accent hover:underline">
            News
          </Link>{" "}
          are not all the same thing, and every card in that grid is badged so you never have to guess which you are
          reading.
        </p>
        <p>
          <strong className="font-semibold text-accent">Measured</strong> — {REPORTS.length} data reports. Every figure
          in them was computed from the TCGplayer price snapshot on a stated date, and{" "}
          <code className="font-mono text-[13px] text-ink">scripts/verify-reports.ts</code> re-derives all of them from
          the source data before the site builds, failing the build if any has drifted. They are bylined to an automated
          desk rather than a persona, because real analysis under an invented human byline would be worse than no byline
          at all. They describe the market; they do not predict it, and they are not advice.
        </p>
        <p>
          <strong className="font-semibold text-down">Demo</strong> — {ARTICLES.length - REPORTS.length} illustrative
          pieces. They discuss real cards, but the market activity, tournament results and price movements they describe
          are invented, as is the analysis, and their bylines are the fictional personas above. Nothing in them is a
          record of anything that happened.
        </p>
      </Section>

      <Section title="What is real">
        <p>
          The catalogue: {CARDS.length} cards across {SETS.length} sets ({SETS.map((s) => s.name).join(", ")}), with
          their genuine names, collector numbers, rarities, domains, types, stats and official artwork. Set release
          dates and card counts are as published.
        </p>
      </Section>

      <Section title="Privacy">
        <p>
          {ACCOUNTS_ENABLED
            ? "This site runs no analytics and loads no advertising. The only cookie it sets is a functional one that keeps you signed in, and only if you create an account."
            : "This site sets no cookies, runs no analytics and loads no advertising."}{" "}
          Your theme and currency preferences are stored in your own browser. See the{" "}
          <Link href="/privacy" className="text-accent hover:underline">
            privacy page
          </Link>{" "}
          for detail.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Corrections and takedown requests:{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-accent hover:underline">
            {CONTACT_EMAIL}
          </a>
          .
        </p>
      </Section>
    </div>
  );
}
